/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param spender The ss-58 encoded address
 * @param collectionId 
 * @param tokenId 
 * @param isApprove 
 */


data class ApproveTokenBody (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    /* The ss-58 encoded address */
    @Json(name = "spender")
    val spender: kotlin.String,

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    @Json(name = "tokenId")
    val tokenId: java.math.BigDecimal,

    @Json(name = "isApprove")
    val isApprove: kotlin.Boolean

)

