/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param collectionId 
 * @param tokenId 
 * @param address The ss-58 encoded address
 * @param from The ss-58 encoded address
 * @param `value` 
 */


data class BurnTokenBody (

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    @Json(name = "tokenId")
    val tokenId: java.math.BigDecimal,

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    /* The ss-58 encoded address */
    @Json(name = "from")
    val from: kotlin.String? = null,

    @Json(name = "value")
    val `value`: java.math.BigDecimal? = null

)

