/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.CollectionNestingPermissionsDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param access 
 * @param mintMode 
 * @param nesting 
 */


data class CollectionPermissionsDto (

    @Json(name = "access")
    val access: CollectionPermissionsDto.Access? = null,

    @Json(name = "mintMode")
    val mintMode: kotlin.Boolean? = null,

    @Json(name = "nesting")
    val nesting: CollectionNestingPermissionsDto? = null

) {

    /**
     * 
     *
     * Values: normal,allowList
     */
    enum class Access(val value: kotlin.String) {
        @Json(name = "Normal") normal("Normal"),
        @Json(name = "AllowList") allowList("AllowList");
    }
}

