/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.CollectionPropertyKeyPermissionPermission

import com.squareup.moshi.Json

/**
 * 
 *
 * @param key 
 * @param permission 
 */


data class CollectionPropertyKeyPermission (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "permission")
    val permission: CollectionPropertyKeyPermissionPermission

)

