/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.TokenProperty

import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param collectionId 
 * @param owner 
 * @param properties 
 * @param url 
 * @param suffix 
 */


data class CreateERC721TokenBody (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.List<TokenProperty>? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "suffix")
    val suffix: kotlin.String? = null

)

