/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param underscore 
 */


data class DecodedAttributeDtoName (

    @Json(name = "_")
    val underscore: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.String>()

