/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.TokenPropertyDeletedEvent

import com.squareup.moshi.Json

/**
 * 
 *
 * @param properties 
 */


data class DeleteTokenPropertiesParsed (

    @Json(name = "properties")
    val properties: kotlin.collections.List<TokenPropertyDeletedEvent>

)

