/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.EvmContractExistsArgumentsDtoBlockNumber

import com.squareup.moshi.Json

/**
 * 
 *
 * @param contractAddress Ethereum address of your smart contract
 * @param blockNumber 
 */


data class EvmContractExistsArgumentsDto (

    /* Ethereum address of your smart contract */
    @Json(name = "contractAddress")
    val contractAddress: kotlin.String,

    @Json(name = "blockNumber")
    val blockNumber: EvmContractExistsArgumentsDtoBlockNumber? = null

)

