/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.EvmEventDto
import network.unique.model.UnknownEventDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param isExecutedFailed 
 * @param parsedEvents 
 * @param unknownEvents 
 */


data class EvmSendResultParsed (

    @Json(name = "isExecutedFailed")
    val isExecutedFailed: kotlin.Boolean,

    @Json(name = "parsedEvents")
    val parsedEvents: kotlin.collections.List<EvmEventDto>,

    @Json(name = "unknownEvents")
    val unknownEvents: kotlin.collections.List<UnknownEventDto>

)

