/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param use 
 * @param withFee 
 * @param verify 
 * @param callbackUrl 
 * @param nonce 
 */


data class MutationQuery (

    @Json(name = "use")
    val use: MutationQuery.Use? = null,

    @Json(name = "withFee")
    val withFee: kotlin.Boolean? = false,

    @Json(name = "verify")
    val verify: kotlin.Boolean? = false,

    @Json(name = "callbackUrl")
    val callbackUrl: kotlin.String? = null,

    @Json(name = "nonce")
    val nonce: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: build,buildBatch,sign,submit,submitWatch,result
     */
    enum class Use(val value: kotlin.String) {
        @Json(name = "Build") build("Build"),
        @Json(name = "BuildBatch") buildBatch("BuildBatch"),
        @Json(name = "Sign") sign("Sign"),
        @Json(name = "Submit") submit("Submit"),
        @Json(name = "SubmitWatch") submitWatch("SubmitWatch"),
        @Json(name = "Result") result("Result");
    }
}

