/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param collectionId 
 * @param admin The ss-58 encoded address
 */


data class RemoveCollectionAdminParsed (

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    /* The ss-58 encoded address */
    @Json(name = "admin")
    val admin: kotlin.String

)

