/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.TokenProperty

import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param collectionId 
 * @param tokenId 
 * @param properties 
 */


data class SetTokenPropertiesBody (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    @Json(name = "tokenId")
    val tokenId: java.math.BigDecimal,

    @Json(name = "properties")
    val properties: kotlin.collections.List<TokenProperty>

)

