/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param recipient The ss-58 encoded address
 * @param amount 
 * @param collectionId 
 */


data class TransferTokensArgsDto (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    /* The ss-58 encoded address */
    @Json(name = "recipient")
    val recipient: kotlin.String,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal

)

