/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param section 
 * @param method 
 * @param args 
 */


data class TxBuildBody (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "section")
    val section: kotlin.String,

    @Json(name = "method")
    val method: kotlin.String,

    @Json(name = "args")
    val args: kotlin.collections.List<Any>

)

