/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ipfsCid 
 * @param hash 
 */


data class UniqueCollectionSchemaDecodedDtoCoverPictureOneOf2 (

    @Json(name = "ipfsCid")
    val ipfsCid: kotlin.String? = null,

    @Json(name = "hash")
    val hash: kotlin.String? = null

)

