/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.NestTokenBodyNested
import network.unique.model.NestTokenBodyParent

import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param parent 
 * @param nested 
 * @param `value` 
 */


data class UnnestTokenBody (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "parent")
    val parent: NestTokenBodyParent,

    @Json(name = "nested")
    val nested: NestTokenBodyNested,

    @Json(name = "value")
    val `value`: java.math.BigDecimal? = java.math.BigDecimal("1")

)

