/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.TokenId

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tokens 
 */


data class AccountTokensResponse (

    @Json(name = "tokens")
    val tokens: kotlin.collections.List<TokenId>? = null

)

