/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.BalanceResponse

import com.squareup.moshi.Json

/**
 * 
 *
 * @param availableBalance 
 * @param lockedBalance 
 * @param freeBalance 
 * @param address The ss-58 encoded address
 */


data class AllBalancesResponse (

    @Json(name = "availableBalance")
    val availableBalance: BalanceResponse? = null,

    @Json(name = "lockedBalance")
    val lockedBalance: BalanceResponse? = null,

    @Json(name = "freeBalance")
    val freeBalance: BalanceResponse? = null,

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String? = null,

)

