/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.AttributeSchemaDtoEnumValuesValue
import network.unique.model.DecodedAttributeDtoName

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param type 
 * @param optional 
 * @param isArray 
 * @param enumValues 
 */


data class AttributeSchemaDto (

    @Json(name = "name")
    val name: DecodedAttributeDtoName? = null,

    @Json(name = "type")
    val type: AttributeSchemaDto.Type? = null,

    @Json(name = "optional")
    val optional: kotlin.Boolean? = null,

    @Json(name = "isArray")
    val isArray: kotlin.Boolean? = null,

    @Json(name = "enumValues")
    val enumValues: kotlin.collections.Map<kotlin.String, AttributeSchemaDtoEnumValuesValue>? = null

) {

    /**
     * 
     *
     * Values: number,integer,float,boolean,timestamp,string,url,isoDate,time,colorRgba
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "number") number("number"),
        @Json(name = "integer") integer("integer"),
        @Json(name = "float") float("float"),
        @Json(name = "boolean") boolean("boolean"),
        @Json(name = "timestamp") timestamp("timestamp"),
        @Json(name = "string") string("string"),
        @Json(name = "url") url("url"),
        @Json(name = "isoDate") isoDate("isoDate"),
        @Json(name = "time") time("time"),
        @Json(name = "colorRgba") colorRgba("colorRgba");
    }
}

