/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.BalanceTransferParsed
import network.unique.model.FeeResponse

import com.squareup.moshi.Json

/**
 * 
 *
 * @param isError 
 * @param parsed 
 * @param fee 
 */


data class BalanceTransferResponse (

    @Json(name = "isError")
    val isError: kotlin.Boolean,

    @Json(name = "parsed")
    val parsed: BalanceTransferParsed,

    @Json(name = "fee")
    val fee: FeeResponse? = null

)

