/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.HeaderResult

import com.squareup.moshi.Json

/**
 * 
 *
 * @param hash 
 * @param header 
 */


data class BlockResult (

    @Json(name = "hash")
    val hash: kotlin.String? = null,

    @Json(name = "header")
    val header: HeaderResult? = null,

)

