/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ss58Prefix 
 * @param token 
 * @param decimals 
 * @param wsUrl 
 * @param genesisHash 
 */


data class ChainPropertiesResponse (

    @Json(name = "SS58Prefix")
    val ss58Prefix: java.math.BigDecimal,

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "decimals")
    val decimals: java.math.BigDecimal,

    @Json(name = "wsUrl")
    val wsUrl: kotlin.String,

    @Json(name = "genesisHash")
    val genesisHash: kotlin.String

)

