/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json
import java.math.BigDecimal

/**
 * 
 *
 * @param tokenOwner 
 * @param collectionAdmin 
 * @param restricted 
 */


data class CollectionNestingPermissionsDto (

    @Json(name = "tokenOwner")
    val tokenOwner: kotlin.Boolean? = null,

    @Json(name = "collectionAdmin")
    val collectionAdmin: kotlin.Boolean? = null,

    @Json(name = "restricted")
    val restricted: kotlin.collections.List<java.math.BigDecimal>? = arrayListOf(BigDecimal(1),BigDecimal(2))

)

