/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.TokenProperty
import network.unique.model.UniqueTokenToCreateDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param collectionId 
 * @param amount 
 * @param owner The ss-58 encoded address
 * @param `data` 
 * @param properties 
 */


data class CreateRefungibleTokenRequest (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    /* The ss-58 encoded address */
    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "data")
    val `data`: UniqueTokenToCreateDto? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.List<TokenProperty>? = null

)

