/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.EffectiveCollectionLimitsResponseLimits

import com.squareup.moshi.Json

/**
 * 
 *
 * @param collectionId 
 * @param limits 
 */


data class EffectiveCollectionLimitsResponse (

    @Json(name = "collectionId")
    val collectionId: java.math.BigDecimal? = null,

    @Json(name = "limits")
    val limits: EffectiveCollectionLimitsResponseLimits? = null,

)

