/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.ExtrinsicResultEvent
import network.unique.model.FeeResponse

import com.squareup.moshi.Json

/**
 * 
 *
 * @param status 
 * @param isCompleted 
 * @param isError 
 * @param blockHash 
 * @param blockIndex 
 * @param error 
 * @param events 
 * @param callbackUrl 
 * @param useMethod 
 * @param parsed 
 * @param fee 
 */


data class ExtrinsicResultResponse (

    @Json(name = "status")
    val status: kotlin.String?,

    @Json(name = "isCompleted")
    val isCompleted: kotlin.Boolean?,

    @Json(name = "isError")
    val isError: kotlin.Boolean?,

    @Json(name = "blockHash")
    val blockHash: kotlin.String?,

    @Json(name = "blockIndex")
    val blockIndex: java.math.BigDecimal?,

    @Json(name = "error")
    val error: kotlin.Any?,

    @Json(name = "events")
    val events: kotlin.collections.List<ExtrinsicResultEvent>?,

    @Json(name = "callbackUrl")
    val callbackUrl: kotlin.String?,

    @Json(name = "useMethod")
    val useMethod: kotlin.Boolean = false,

    @Json(name = "parsed")
    val parsed: kotlin.Any? = null,

    @Json(name = "fee")
    val fee: FeeResponse? = null

)

