/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param section 
 * @param method 
 * @param `data` 
 * @param meta 
 * @param index 
 */


data class ExtrinsicResultEvent (

    @Json(name = "section")
    val section: kotlin.String,

    @Json(name = "method")
    val method: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.Any,

    @Json(name = "meta")
    val meta: kotlin.Any,

    @Json(name = "index")
    val index: kotlin.String

)

