/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param raw 
 * @param amount 
 * @param formatted 
 * @param unit 
 * @param decimals 
 */


data class FeeResponse (

    @Json(name = "raw")
    val raw: kotlin.String? = null,

    @Json(name = "amount")
    val amount: kotlin.String? = null,

    @Json(name = "formatted")
    val formatted: kotlin.String? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null,

    @Json(name = "decimals")
    val decimals: java.math.BigDecimal? = null,

)

