/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.CollectionLimitsDto
import network.unique.model.CollectionPermissionsDto
import network.unique.model.CollectionSponsorship

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param description 
 * @param tokenPrefix 
 * @param decimals 
 * @param id 
 * @param owner The ss-58 encoded address
 * @param mode 
 * @param sponsorship 
 * @param limits 
 * @param metaUpdatePermission 
 * @param permissions 
 * @param readOnly 
 */


data class FungibleCollectionInfoDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "tokenPrefix")
    val tokenPrefix: kotlin.String? = null,

    @Json(name = "decimals")
    val decimals: java.math.BigDecimal? = null,

    @Json(name = "id")
    val id: java.math.BigDecimal? = null,

    /* The ss-58 encoded address */
    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "mode")
    val mode: FungibleCollectionInfoDto.Mode? = null,

    @Json(name = "sponsorship")
    val sponsorship: CollectionSponsorship? = null,

    @Json(name = "limits")
    val limits: CollectionLimitsDto? = null,

    @Json(name = "metaUpdatePermission")
    val metaUpdatePermission: FungibleCollectionInfoDto.MetaUpdatePermission? = null,

    @Json(name = "permissions")
    val permissions: CollectionPermissionsDto? = null,

    @Json(name = "readOnly")
    val readOnly: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: nFT,fungible,reFungible
     */
    enum class Mode(val value: kotlin.String) {
        @Json(name = "NFT") nFT("NFT"),
        @Json(name = "Fungible") fungible("Fungible"),
        @Json(name = "ReFungible") reFungible("ReFungible");
    }
    /**
     * 
     *
     * Values: itemOwner,admin,none
     */
    enum class MetaUpdatePermission(val value: kotlin.String) {
        @Json(name = "ItemOwner") itemOwner("ItemOwner"),
        @Json(name = "Admin") admin("Admin"),
        @Json(name = "None") none("None");
    }
}

