/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.EvmContractExistsArgumentsDtoBlockNumber

import com.squareup.moshi.Json

/**
 * 
 *
 * @param blockHashOrNumber 
 * @param extrinsicHash 
 */


data class GetExtrinsicQuery (

    @Json(name = "blockHashOrNumber")
    val blockHashOrNumber: EvmContractExistsArgumentsDtoBlockNumber? = null,

    @Json(name = "extrinsicHash")
    val extrinsicHash: kotlin.String? = null,

)

