/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param created 
 * @param destroyed 
 * @param alive 
 */


data class GetStatsResponse (

    @Json(name = "created")
    val created: java.math.BigDecimal? = null,

    @Json(name = "destroyed")
    val destroyed: java.math.BigDecimal? = null,

    @Json(name = "alive")
    val alive: java.math.BigDecimal? = null,

)

