/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param encoded 
 * @param encoding 
 * @param address 
 * @param meta 
 */


data class KeyringPairJsonDto (

    @Json(name = "encoded")
    val encoded: kotlin.String,

    @Json(name = "encoding")
    val encoding: kotlin.Any,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "meta")
    val meta: kotlin.Any

)

