/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param section 
 * @param method 
 */


data class MethodNameDto (

    @Json(name = "section")
    val section: kotlin.String? = null,

    @Json(name = "method")
    val method: kotlin.String? = null,

)

