/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param address The ss-58 encoded address
 * @param `data` The hex-encoded data for this request
 * @param type The type of the contained data
 */


data class SignerPayloadRawDto (

    /* The ss-58 encoded address */
    @Json(name = "address")
    val address: kotlin.String? = null,

    /* The hex-encoded data for this request */
    @Json(name = "data")
    val `data`: kotlin.String? = null,

    /* The type of the contained data */
    @Json(name = "type")
    val type: SignerPayloadRawDto.Type? = null,

) {

    /**
     * The type of the contained data
     *
     * Values: bytes,payload
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "bytes") bytes("bytes"),
        @Json(name = "payload") payload("payload");
    }
}

