/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param signature 
 * @param signatureType 
 */


data class SignTxResultResponse (

    @Json(name = "signature")
    val signature: kotlin.String,

    @Json(name = "signatureType")
    val signatureType: SignTxResultResponse.SignatureType

) {

    /**
     * 
     *
     * Values: sr25519,ed25519,ecdsa,ethereum
     */
    enum class SignatureType(val value: kotlin.String) {
        @Json(name = "sr25519") sr25519("sr25519"),
        @Json(name = "ed25519") ed25519("ed25519"),
        @Json(name = "ecdsa") ecdsa("ecdsa"),
        @Json(name = "ethereum") ethereum("ethereum");
    }
}

