/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model

import network.unique.model.DecodedAttributeDtoName
import network.unique.model.UniqueTokenToCreateDtoAttributesValue
import network.unique.model.UniqueTokenToCreateDtoEncodedAttributesValue
import network.unique.model.UniqueTokenToCreateDtoImage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param image 
 * @param attributes 
 * @param encodedAttributes 
 * @param name 
 * @param audio 
 * @param description 
 * @param imagePreview 
 * @param spatialObject 
 * @param video 
 */


data class UniqueTokenToCreateDto (

    @Json(name = "image")
    val image: UniqueTokenToCreateDtoImage? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, UniqueTokenToCreateDtoAttributesValue>? = null,

    @Json(name = "encodedAttributes")
    val encodedAttributes: kotlin.collections.Map<kotlin.String, UniqueTokenToCreateDtoEncodedAttributesValue>? = null,

    @Json(name = "name")
    val name: DecodedAttributeDtoName? = null,

    @Json(name = "audio")
    val audio: UniqueTokenToCreateDtoImage? = null,

    @Json(name = "description")
    val description: DecodedAttributeDtoName? = null,

    @Json(name = "imagePreview")
    val imagePreview: UniqueTokenToCreateDtoImage? = null,

    @Json(name = "spatialObject")
    val spatialObject: UniqueTokenToCreateDtoImage? = null,

    @Json(name = "video")
    val video: UniqueTokenToCreateDtoImage? = null

)

