/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package network.unique.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param isValid 
 * @param errorMessage 
 */


data class VerificationResultResponse (

    @Json(name = "isValid")
    val isValid: kotlin.Boolean? = null,

    @Json(name = "errorMessage")
    val errorMessage: kotlin.String? = null,

)

